{% set version = "0.0.18" %}

package:
  name: gnss-sdr-split
  version: {{ version }}

source:
  url: https://github.com/gnss-sdr/gnss-sdr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d5533370de188d50c214a5bb7832a433ceb09369c3e3296a4fa34fa1aefb685e
  patches:
    - 0001-cmake-Manually-specify-compiled-in-GNSSSDR_INSTALL_D.patch
    - 0002-cmake-Prefer-using-CMake-config-files-for-Gnuradio-a.patch
    - 0003-observables-gnuradio_blocks-Link-obs_gr_blocks-with-.patch
    - 0004-cmake-Allow-global-C-C-std-to-be-overridden-from-com.patch

build:
  number: 19
  skip: true  # [win]

outputs:
  - name: volk-gnss-sdr
    script: build-volk-gnss-sdr.sh  # [unix]
    script: bld-volk-gnss-sdr.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('volk-gnss-sdr', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - gstreamer-orc  # [not win]
        - mako
        - ninja
        - pkg-config
        - python >=3.7
      host:
        - gstreamer-orc  # [not win]
      run:
        - {{ pin_compatible('gstreamer-orc', max_pin='x.x') }}  # [not win]
    test:
      commands:
        # verify that commands run
        - volk_gnsssdr-config-info --version --prefix --cc --cflags --all-machines --avail-machines --machine --alignment --malloc
        - volk_gnsssdr_profile --help

        # verify that headers get installed
        - test -f $PREFIX/include/volk_gnsssdr/volk_gnsssdr.h  # [not win]
        - if not exist %PREFIX%\\Library\\include\\volk_gnsssdr\\volk_gnsssdr.h exit 1  # [win]

        # verify libraries
        - test -f $PREFIX/lib/libvolk_gnsssdr${SHLIB_EXT}  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\volk_gnsssdr.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\volk_gnsssdr.lib exit 1  # [win]

        # verify that CMake files get installed
        - test -f $PREFIX/lib/cmake/volk_gnsssdr/VolkGnsssdrConfig.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\volk_gnsssdr\\VolkGnsssdrConfig.cmake exit 1  # [win]

        # verify that pkgconfig file gets installed
        - test -f $PREFIX/lib/pkgconfig/volk_gnsssdr.pc  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\volk_gnsssdr.pc exit 1  # [win]

  - name: gnss-sdr
    script: build-gnss-sdr.sh  # [unix]
    script: bld-gnss-sdr.bat  # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - git
        - libprotobuf  # [build_platform != target_platform]
        - ninja
        - pkg-config
      host:
        - armadillo
        - libboost-devel
        - gflags
        - glog
        - gnuradio-core
        - gnuradio-iio
        - gnuradio-osmosdr
        - gnuradio-uhd
        - gnuradio-zeromq
        - libad9361-iio
        - libblas
        - libiio
        - liblapack
        - libmatio
        - libpcap
        - libprotobuf
        - openssl
        - protobuf
        - pugixml
        - uhd
        - volk
        - {{ pin_subpackage('volk-gnss-sdr', exact=True) }}
      run:
        - {{ pin_compatible('gnuradio-iio', max_pin='x.x.x') }}
        - {{ pin_compatible('gnuradio-uhd', max_pin='x.x.x') }}
        - {{ pin_compatible('gnuradio-zeromq', max_pin='x.x.x') }}
        - {{ pin_subpackage('volk-gnss-sdr', exact=True) }}
    test:
      commands:
        # verify that commands run
        - front-end-cal --version
        - gnss-sdr --version

        # verify that default and example config files get installed
        - test -f $PREFIX/share/gnss-sdr/conf/default.conf  # [not win]
        - test -f $PREFIX/share/gnss-sdr/conf/gnss-sdr.conf  # [not win]
        - if not exist %PREFIX%\\Library\\share\\gnss-sdr\\conf\\default.conf exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\gnss-sdr\\conf\\gnss-sdr.conf exit 1  # [win]

about:
  home: https://gnss-sdr.org/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: 'An open-source software-defined GNSS receiver'
  description: >
    This program is a software-defined receiver which is able to process (that
    is, to perform detection, synchronization, demodulation and decoding of the
    navigation message, computation of observables, and, finally, computation of
    position fixes) the following Global Navigation Satellite System's signals:

    In the L1 band:

        - GLONASS L1 C/A (centered at 1602.000 MHz)
        - GPS L1 C/A (centered at 1575.420 MHz)
        - Galileo E1b/c (centered at 1575.420 MHz)
        - BeiDou B1I (centered at 1561.098 MHz)

    In the E6 band:

        - Galileo E6B (centered at 1278.750 MHz)

    In the L2 band:

        - BeiDou B3I (centered at 1268.520 MHz)
        - GLONASS L2 C/A (centered at 1246.000 MHz)
        - GPS L2C (centered at 1227.600 MHz)

    In the L5 band:

        - Galileo E5b (centered at 1207.140 MHz)
        - Galileo E5a (centered at 1176.450 MHz)
        - GPS L5 (centered at 1176.450 MHz)

    GNSS-SDR provides interfaces for a wide range of radio frequency front-ends
    and raw sample file formats, generates processing outputs in standard
    formats, allows for the full inspection of the whole signal processing
    chain, and offers a framework for the development of new features.
  doc_url: https://gnss-sdr.org/docs/
  dev_url: https://github.com/gnss-sdr/gnss-sdr

extra:
  feedstock-name: gnss-sdr
  recipe-maintainers:
    - ryanvolz
